server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LikeList?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: yccycc0916
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

logging:
  level:
    com.ycc.likelist: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
